wnsl1364/Kimbap

kbs/frontend/src/layout/AppMenu.vue, kbs/frontend/src/main.js, kbs/frontend/src/router/index.js, kbs/frontend/src/router/logistics.js, kbs/frontend/src/router/material.js, kbs/frontend/src/router/order.js, kbs/frontend/src/router/payment.js, kbs/frontend/src/router/production.js, kbs/frontend/src/views/material/MaterialStockView.vue
=> 라우터 세팅_2025-07-21_다산

kbs/frontend/src/layout/AppMenu.vue, kbs/frontend/src/router/material.js, kbs/frontend/src/views/material/MaterialInOutHistory.vue, kbs/frontend/src/views/material/MaterialInbound.vue, kbs/frontend/src/views/material/MaterialLoadingWaitingList.vue, kbs/frontend/src/views/material/TransferRequestForm.vue, kbs/frontend/src/views/material/TransferRequestList.vue
=> 자재목록 세팅_다산

kbs/frontend/src/views/material/MaterialInbound.vue
=> 20250722-다산-자재입고 틀 만듬

kbs/backend/pom.xml, kbs/backend/src/main/java/com/kimbap/kbs/mapper/MemberMapper.java, kbs/backend/src/main/java/com/kimbap/kbs/web/LoginController.java, kbs/backend/src/main/resources/application.properties.example, kbs/backend/src/main/resources/mapper/member/member.xml, kbs/frontend/package-lock.json, kbs/frontend/package.json, kbs/frontend/src/router/index.js, kbs/frontend/src/views/login/LoginForm.vue, kbs/frontend/vite.config.mjs
=> 2025-07-22 심재진 로그인

kbs/frontend/src/components/kimbap/modal/multipleselect.vue, kbs/frontend/src/views/material/MaterialInbound.vue
=> 20250723-산-모달

kbs/frontend/package-lock.json, kbs/frontend/src/views/material/MaterialInbound.vue
=> 20250723-산-중간머징

kbs/frontend/src/components/kimbap/table/BasicTable.vue, kbs/frontend/src/stores/materialStore.js, kbs/frontend/src/views/material/MaterialInbound.vue
=> 20250723-김다산-베이직테이블 수정

kbs/frontend/src/components/kimbap/searchform/SearchForm.vue, kbs/frontend/src/components/kimbap/table/BasicTable.vue, kbs/frontend/src/components/kimbap/table/InputTable.vue, kbs/frontend/src/stores/materialStore.js, kbs/frontend/src/views/material/MaterialOutbound.vue, kbs/frontend/src/views/material/MaterialPurchase.vue, kbs/frontend/src/views/material/MaterialPurchaseConfirm.vue, kbs/frontend/src/views/material/MaterialPurchaseView.vue
- 검색 폼 및 테이블에 readonly 필드 추가
- 구매/발주 관련 데이터 및 상태 관리 기능 구현
- 내부직원 및 공급업체직원에 따른 검색 조건 및 테이블 컬럼 설정
- 버튼 숨기기 및 이벤트 핸들러 추가
=> 20250724-이준영-기능: 자재 구매/발주 관리 화면 추가 및 검색 폼, 테이블 구성

kbs/backend/src/main/resources/mapper/materials/MateMapper.xml
=> 20250724-김다산-서버에러 해결

kbs/backend/src/main/java/com/kimbap/kbs/materials/mapper/MateMapper.java, kbs/backend/src/main/java/com/kimbap/kbs/materials/service/MateService.java, kbs/backend/src/main/java/com/kimbap/kbs/materials/service/MaterialsVO.java, kbs/backend/src/main/java/com/kimbap/kbs/materials/service/SearchCriteria.java, kbs/backend/src/main/java/com/kimbap/kbs/materials/serviceimpl/MateServiceImpl.java, kbs/backend/src/main/java/com/kimbap/kbs/materials/web/MateController.java, kbs/backend/src/main/java/com/kimbap/kbs/security/config/SecurityConfig.java, kbs/backend/src/main/resources/mapper/materials/MateMapper.xml, kbs/frontend/src/api/materials.js, kbs/frontend/src/views/material/MaterialPurchase.vue
feat: 구매주문 관리 기능 구현
- 구매주문 조회, 저장, 구매코드 생성을 위한 API 함수들을 추가함
- MaterialPurchase.vue 컴포넌트를 강화하여 구매주문 생성 및 로딩 기능을 지원함
- date-fns 라이브러리를 활용하여 날짜 포맷팅 및 검증 기능을 향상시킴
- 로딩, 저장, 오류 상황에 대한 토스트 알림 기능을 통합하여 사용자 경험을 개선함
- 구매주문 프로세스에서 자재 및 공급업체 통합을 지원하도록 데이터 구조를 업데이트함
- 구매주문의 총 품목 수, 공급업체 수, 총액을 표시하는 요약 섹션을 추가함
=> 20250729-이준영

kbs/backend/src/main/resources/mapper/materials/MateLoadingMapper.xml, kbs/frontend/src/api/materials.js, kbs/frontend/src/components/kimbap/table/InputTable.vue, kbs/frontend/src/stores/mateLoadingStore.js, kbs/frontend/src/views/material/MateLoading.vue
=> 20250731-김다산-중간커밋

kbs/backend/src/main/java/com/kimbap/kbs/materials/mapper/MateMapper.java, kbs/backend/src/main/java/com/kimbap/kbs/materials/service/MateService.java, kbs/backend/src/main/java/com/kimbap/kbs/materials/service/PurchaseOrderViewVO.java, kbs/backend/src/main/java/com/kimbap/kbs/materials/serviceimpl/MateServiceImpl.java, kbs/backend/src/main/java/com/kimbap/kbs/materials/web/MateController.java, kbs/backend/src/main/resources/mapper/materials/MateMapper.xml, kbs/frontend/src/api/materials.js, kbs/frontend/src/components/kimbap/table/InputTable.vue, kbs/frontend/src/stores/materialStore.js, kbs/frontend/src/views/material/MaterialPurchase.vue, kbs/frontend/src/views/material/MaterialPurchaseApproval.vue, kbs/frontend/src/views/material/MaterialPurchaseView.vue
refactor: Replace searchPurchaseOrders with getPurchaseOrdersForView API and clean up data handling in MaterialPurchaseView.vue
=> 20250731-이준영

kbs/frontend/src/components/kimbap/table/InputTable.vue, kbs/frontend/src/stores/mateLoadingStore.js
=> 20250731-김다산

kbs/backend/src/main/java/com/kimbap/kbs/materials/mapper/MateMapper.java, kbs/backend/src/main/java/com/kimbap/kbs/materials/service/MateService.java, kbs/backend/src/main/java/com/kimbap/kbs/materials/service/MaterialsVO.java, kbs/backend/src/main/java/com/kimbap/kbs/materials/service/PurchaseOrderViewVO.java, kbs/backend/src/main/java/com/kimbap/kbs/materials/serviceimpl/MateServiceImpl.java, kbs/backend/src/main/java/com/kimbap/kbs/materials/web/MateController.java, kbs/backend/src/main/resources/mapper/materials/MateMapper.xml, kbs/frontend/src/layout/AppMenu.vue, kbs/frontend/src/router/material.js, kbs/frontend/src/views/material/MaterialOutbound.vue, kbs/frontend/src/views/material/MaterialPurchaseApproval.vue, kbs/frontend/src/views/material/TestStore.vue
feat: 공급업체-자재 관계 조회 기능 추가 및 창고 관리 UI 개선
- 다양한 조건에 따른 공급업체-자재 관계를 가져오는 새로운 엔드포인트를 MateController에 구현
- 새로운 기능에 필요한 SQL 쿼리를 MateMapper.xml에 추가
- 고급 창고 관리를 위한 새로운 TestStore.vue 컴포넌트 추가, 사용자가 보관 구역을 시각화하고 관리할 수 있도록 지원
- 주문 세부사항 및 수량 표시 개선을 위해 MaterialOutbound.vue 향상
- 새로운 TestStore 뷰를 포함하도록 라우팅 업데이트
- 새로운 창고 관리 기능에 대한 내비게이션을 추가하기 위해 AppMenu.vue 개선
=> 20250801-이준영

kbs/backend/src/main/java/com/kimbap/kbs/materials/service/SearchCriteria.java, kbs/backend/src/main/java/com/kimbap/kbs/materials/serviceimpl/MateServiceImpl.java, kbs/backend/src/main/java/com/kimbap/kbs/materials/web/MateController.java, kbs/backend/src/main/java/com/kimbap/kbs/security/filter/JwtAuthenticationFilter.java, kbs/backend/src/main/java/com/kimbap/kbs/security/util/JwtUtil.java, kbs/backend/src/main/resources/mapper/materials/MateMapper.xml, kbs/frontend/src/api/materials.js, kbs/frontend/src/api/member.js, kbs/frontend/src/stores/materialStore.js, kbs/frontend/src/views/material/MaterialOutbound.vue
feat: Enhance JWT authentication and material outbound processing
- Improved JwtAuthenticationFilter to extract and store cpCd from JWT tokens.
- Added detailed logging for JWT token processing and validation.
- Updated JwtUtil to include methods for extracting cpCd from tokens and validating tokens with detailed logging.
- Modified MateMapper.xml to enhance supplier material release query with additional filtering options.
- Implemented new API functions in materials.js for supplier material release and outbound processing.
- Added axios interceptors in member.js for automatic token handling and error management.
- Expanded materialStore.js to manage outbound data, selected materials, and statistics.
- Revamped MaterialOutbound.vue to integrate new features for searching, displaying, and …
=> 20250804-이준영

kbs/backend/src/main/java/com/kimbap/kbs/materials/mapper/MateMapper.java, kbs/backend/src/main/java/com/kimbap/kbs/materials/service/MateService.java, kbs/backend/src/main/java/com/kimbap/kbs/materials/service/MaterialsVO.java, kbs/backend/src/main/java/com/kimbap/kbs/materials/serviceimpl/MateServiceImpl.java, kbs/backend/src/main/java/com/kimbap/kbs/materials/web/MateController.java, kbs/backend/src/main/resources/mapper/materials/MateMapper.xml, kbs/frontend/src/views/material/MaterialOutbound.vue
자재 출고 처리 로직 개선 및 curr_qty와 상태 동시 업데이트 기능 추가
=> 20250805-이준영

kbs/backend/src/main/java/com/kimbap/kbs/distribution/mapper/DistributionMapper.java, kbs/backend/src/main/java/com/kimbap/kbs/distribution/service/DistributionService.java, kbs/backend/src/main/java/com/kimbap/kbs/distribution/service/RelOrdModalVO.java, kbs/backend/src/main/java/com/kimbap/kbs/distribution/service/WarehouseVO.java, kbs/backend/src/main/java/com/kimbap/kbs/distribution/serviceimpl/DistributionServiceImpl.java, kbs/backend/src/main/java/com/kimbap/kbs/distribution/web/DistributionController.java, kbs/backend/src/main/resources/mapper/distribution/DistributionMapper.xml, kbs/frontend/src/api/distribution.js, kbs/frontend/src/components/kimbap/table/InputTable.vue, kbs/frontend/src/components/kimbap/table/LeftAlignTable.vue, kbs/frontend/src/views/distribution/RelOrdAndResult.vue, kbs/frontend/src/views/standard/warehouse.vue
=> 2025-08-07 심재진

kbs/backend/src/main/java/com/kimbap/kbs/materials/mapper/MateMapper.java, kbs/backend/src/main/java/com/kimbap/kbs/materials/service/MateService.java, kbs/backend/src/main/java/com/kimbap/kbs/materials/service/MaterialsVO.java, kbs/backend/src/main/java/com/kimbap/kbs/materials/serviceimpl/MateServiceImpl.java, kbs/backend/src/main/java/com/kimbap/kbs/materials/web/MateController.java, kbs/backend/src/main/resources/mapper/materials/MateMapper.xml, kbs/frontend/src/api/materials.js, kbs/frontend/src/stores/materialStore.js, kbs/frontend/src/views/material/MaterialPurchaseView.vue, kbs/frontend/src/views/material/MaterialStockView.vue
기능: 자재 재고 상태 조회 및 관련 기능 구현
내용:
1. 데이터베이스 레이어 -자재 재고 상태 조회용 SQL 쿼리 추가
-자재 코드, 이름, 유형 정보 포함
-공장 정보 및 재고 수량 데이터
-재고 상태 정보까지 한 번에 조회 가능
2.API 레이어
-getMaterialStockStatus API 함수 생-성
-새로운 백엔드 엔드포인트와 연동
-재고 상태 데이터 fetch 기능
3.상태 관리 (Store)
-자재 스토어 기능 확장
-재고 상태 데이터 관리
-통계 정보 처리
-알림 시스템 연동
4.UI 컴포넌트
-MaterialStockView 컴포넌트 개발
-재고 상태 화면 표시
-검색 기능 통합
-엑셀 내보내기 기능
5.부가 기능들
-검색 폼과 입력 테이블 연동
-재고 상태 엑셀 다운로드 기능
-재고 알림 조회 기능
=> 20250807-이준영

kbs/frontend/src/api/materials.js, kbs/frontend/src/views/material/MateLoading.vue, kbs/frontend/src/views/material/MaterialInOutHistory.vue, kbs/frontend/src/views/material/MaterialPurchase.vue, kbs/frontend/src/views/material/MaterialPurchaseApproval.vue, kbs/frontend/src/views/material/MaterialPurchaseView.vue, kbs/frontend/src/views/material/MaterialStockView.vue
자재 관련 API 및 UI 개선: 발주 상세 조회 시 공급업체 필터링 추가, UI 요소 제목 및 스타일 수정
=> 20250811-이준영

kbs/backend/src/main/java/com/kimbap/kbs/distribution/serviceimpl/DistributionServiceImpl.java, kbs/backend/src/main/resources/mapper/dashboard/ChartDataMapper.xml, kbs/backend/src/main/resources/mapper/distribution/DistributionMapper.xml, kbs/frontend/src/views/distribution/DistributionCheck.vue, kbs/frontend/src/views/distribution/RelSave.vue
=> 2025-08-17 심재진 최종수정 완
